### ISSUE TITLE
Bugreport when source-mapping is not turned on

### ISSUE THREAD

**Issue by Evertt** [develar/ts-babel#3]
[This line](https://github.com/develar/ts-babel/blob/master/src/builder.ts#L126) creates an error then. The error disappears if you change it to the following:

```typescript
inputSourceMap: JSON.parse(sourceMap || null),
```

Sorry for not making a PR. O:-)

**Comment by develar** [comment]
I am on vacation. Will be fixed on Saturday. Thanks for bug report.

**Comment by develar** [comment]
Fixed in 1.4.5
